main: tm.info.anna.spigotmc.peacefulai.App
name: PeacefulAI
version: 1.0
api-version: 1.15
commands:
  peaceful:
    description: Sets whether or not the given player is in peaceful mode.
    usage: /<command> <true/false>